### ISSUE TITLE
フォルダ監視機能

### ISSUE THREAD

**Issue by Till0196** [uyorum/gphoto-uploader#1]
MP4のバックアップにGoogle photoを使っているのですが、一つ一つ列挙していくのも面倒ですし、今のところGoogle photoの公式もlinux版を出すような気配はしないので、需要はあると考えられます。なので特定フォルダを自動アップロードするオプション(差分でアップロード)を追加出来ないでしょうか。

**Comment by uyorum** [comment]
一度フォルダを指定すれば、コンテナを作り直さない限りは自動で新しいファイルとサブフォルダを検出してくれるかと思いますが、それでは不十分ということでしょうか。

**Comment by Till0196** [comment]
そんな機能あったのですか。よく読んでいませんでした。申し訳ありません。それで十分です。返信ありがとうございました。
